## EffectConst.gd — 效果系统常量定义
##
## 包含全部 42 个 Hook 常量与效果模式常量。
## Hook 值与规则表 Effect全牌表.xlsx "Hook字典" 工作表严格对应。
class_name EffectConst
extends RefCounted

## ── 效果模式 ──
const MODE_ACTIVE := &"ACTIVE"    ## 主动：玩家在主阶段选择使用
const MODE_PASSIVE := &"PASSIVE"  ## 被动：在 hook 时机自动触发
const MODE_STATIC := &"STATIC"   ## 静态：持续生效，由 STAT_RECALCULATE 重算

## ── 游戏生命周期 ──
const HOOK_GAME_STARTED := &"ON_GAME_STARTED"
const HOOK_GAME_OVER := &"ON_GAME_OVER"

## ── 轮次 ──
const HOOK_ROUND_START := &"ON_ROUND_START"

## ── 回合 ──
const HOOK_TURN_START := &"ON_TURN_START"
const HOOK_MAIN_PHASE_START := &"ON_MAIN_PHASE_START"
const HOOK_OWNER_MAIN_PHASE := &"ON_OWNER_MAIN_PHASE"
const HOOK_TURN_END := &"ON_TURN_END"
const HOOK_OTHER_MECH_TURN_START := &"ON_OTHER_MECH_TURN_START"  ## 其他机甲回合开始时

## ── 卡牌 ──
const HOOK_CARD_PLAYED := &"ON_CARD_PLAYED"
const HOOK_ACTION_CARD_PLAYED := &"ON_ACTION_CARD_PLAYED"
const HOOK_EQUIPMENT_SET := &"ON_EQUIPMENT_SET"
const HOOK_EVENT_SET := &"ON_EVENT_SET"
const HOOK_CARD_DISCARDED := &"ON_CARD_DISCARDED"
const HOOK_CARD_DESTROYED := &"ON_CARD_DESTROYED"

## ── 攻击 ──
const HOOK_ATTACK_CARD_PLAYED := &"ON_ATTACK_CARD_PLAYED"
const HOOK_ATTACK_DECLARED := &"ON_ATTACK_DECLARED"
const HOOK_ATTACK_RESPONSE_WINDOW := &"ON_ATTACK_RESPONSE_WINDOW"
const HOOK_ATTACK_MODIFIER_WINDOW := &"ON_ATTACK_MODIFIER_WINDOW"
const HOOK_ATTACK_HIT := &"ON_ATTACK_HIT"
const HOOK_ATTACK_MISS := &"ON_ATTACK_MISS"
const HOOK_ATTACK_RESOLVED := &"ON_ATTACK_RESOLVED"
const HOOK_MECH_TARGETED_BY_ATTACK := &"ON_MECH_TARGETED_BY_ATTACK"    ## 机甲被指定为攻击目标时(防守方)
const HOOK_MECH_HIT_BY_ATTACK := &"ON_MECH_HIT_BY_ATTACK"              ## 机甲被攻击命中时(防守方)
const HOOK_REACTION_CARD_PLAYED := &"ON_REACTION_CARD_PLAYED"           ## 打出迎击牌时

## ── 伤害 ──
const HOOK_DAMAGE_MODIFIER_WINDOW := &"ON_DAMAGE_MODIFIER_WINDOW"
const HOOK_DAMAGE_DEALT := &"ON_DAMAGE_DEALT"
const HOOK_OWNER_TAKE_DAMAGE := &"ON_OWNER_TAKE_DAMAGE"              ## 我方受到伤害后

## ── 损伤 ──
const HOOK_BEFORE_DAMAGE_TOKEN_PLACED := &"ON_BEFORE_DAMAGE_TOKEN_PLACED"
const HOOK_AFTER_DAMAGE_TOKEN_PLACED := &"ON_AFTER_DAMAGE_TOKEN_PLACED"

## ── 装备 ──
const HOOK_EQUIPMENT_BROKEN := &"ON_EQUIPMENT_BROKEN"
const HOOK_EQUIPMENT_DISCARDED_FROM_SLOT := &"ON_EQUIPMENT_DISCARDED_FROM_SLOT"  ## 装备从区域弃置时
const HOOK_EQUIPMENT_BROKEN_BY_DAMAGE := &"ON_EQUIPMENT_BROKEN_BY_DAMAGE"        ## 装备因损伤弃置时

## ── 胜负 ──
const HOOK_MECH_DESTROYED := &"ON_MECH_DESTROYED"

## ── 事件 ──
const HOOK_EVENT_TIMER_TICK := &"ON_EVENT_TIMER_TICK"
const HOOK_EVENT_TIMER_ZERO := &"ON_EVENT_TIMER_ZERO"

## ── 地图 ──
const HOOK_MECH_MOVED := &"ON_MECH_MOVED"
const HOOK_MECH_LEAVING_CELL := &"ON_MECH_LEAVING_CELL"              ## 机甲离开格子时
const HOOK_MAP_GOLD_MARKER_RESOLVED := &"ON_MAP_GOLD_MARKER_RESOLVED"
const HOOK_MAP_EVENT_MARKER_RESOLVED := &"ON_MAP_EVENT_MARKER_RESOLVED"
const HOOK_TRAP_EXPLODED := &"ON_TRAP_EXPLODED"
const HOOK_MAP_MARKERS_RESET := &"ON_MAP_MARKERS_RESET"

## ── 商店 ──
const HOOK_SHOP_INITIALIZED := &"ON_SHOP_INITIALIZED"
const HOOK_SHOP_CARD_BOUGHT := &"ON_SHOP_CARD_BOUGHT"
const HOOK_SHOP_REFRESHED := &"ON_SHOP_REFRESHED"
const HOOK_SHOP_REFILLED := &"ON_SHOP_REFILLED"

## ── 扩展 ──
const HOOK_STAT_RECALCULATE := &"ON_STAT_RECALCULATE"
const HOOK_STATUS_CHECK := &"ON_STATUS_CHECK"
const HOOK_SHOP_ACTION := &"ON_SHOP_ACTION"
const HOOK_EQUIPMENT_SOLD := &"ON_EQUIPMENT_SOLD"
const HOOK_ACTION_CARD_DRAWN := &"ON_ACTION_CARD_DRAWN"
const HOOK_ENERGY_APPLIED_TO_WEAPON := &"ON_ENERGY_APPLIED_TO_WEAPON"
const HOOK_BEFORE_HEAL := &"ON_BEFORE_HEAL"                          ## 即将回复生命时(拦截)
const HOOK_BEFORE_REMOVE_DAMAGE_TOKENS := &"ON_BEFORE_REMOVE_DAMAGE_TOKENS"  ## 即将移除损伤时(拦截)
const HOOK_OTHER_MECH_GAIN_GOLD := &"ON_OTHER_MECH_GAIN_GOLD"        ## 其他机甲获得金币时
const HOOK_OTHER_MECH_DRAW_ACTION := &"ON_OTHER_MECH_DRAW_ACTION"    ## 其他机甲抽行动牌时

## ── 新增条件常量（机师效果支持） ──
const COND_ATTACK_COUNT_EQUALS := &"ATTACK_COUNT_EQUALS"              ## 攻击次数等于N
const COND_SELF_DAMAGE_TOKENS_BELOW := &"SELF_DAMAGE_TOKENS_BELOW"    ## 此牌损伤<N(slot级)
const COND_SELF_DAMAGE_TOKENS_EQUALS := &"SELF_DAMAGE_TOKENS_EQUALS"  ## 此牌损伤=N(slot级)
const COND_VARIABLE_ABOVE := &"VARIABLE_ABOVE"                        ## 自定义变量X>N

## ── 新增目标规则常量 ──
const TARGET_CHOOSE_MECH_IN_VARIABLE_RANGE := &"CHOOSE_MECH_IN_VARIABLE_RANGE"  ## 选择(基础+变量)范围内的机甲

## ── 新增动作常量 ──
const ACTION_SWAP_HAND_LIMIT_AND_ATTACK_COUNT := &"SWAP_HAND_LIMIT_AND_ATTACK_COUNT"  ## 互换行动牌上限与回合攻击数
