## EffectConst.gd — 效果系统常量定义
##
## 包含全部 42 个 Hook 常量与效果模式常量。
## Hook 值与规则表 Effect全牌表.xlsx "Hook字典" 工作表严格对应。
class_name EffectConst
extends RefCounted

## ── 效果模式 ──
const MODE_ACTIVE := &"ACTIVE"    ## 主动：玩家在主阶段选择使用
const MODE_PASSIVE := &"PASSIVE"  ## 被动：在 hook 时机自动触发
const MODE_STATIC := &"STATIC"   ## 静态：持续生效，由 STAT_RECALCULATE 重算

## ── 游戏生命周期 ──
const HOOK_GAME_STARTED := &"ON_GAME_STARTED"
const HOOK_GAME_OVER := &"ON_GAME_OVER"

## ── 轮次 ──
const HOOK_ROUND_START := &"ON_ROUND_START"

## ── 回合 ──
const HOOK_TURN_START := &"ON_TURN_START"
const HOOK_MAIN_PHASE_START := &"ON_MAIN_PHASE_START"
const HOOK_OWNER_MAIN_PHASE := &"ON_OWNER_MAIN_PHASE"
const HOOK_TURN_END := &"ON_TURN_END"

## ── 卡牌 ──
const HOOK_CARD_PLAYED := &"ON_CARD_PLAYED"
const HOOK_ACTION_CARD_PLAYED := &"ON_ACTION_CARD_PLAYED"
const HOOK_EQUIPMENT_SET := &"ON_EQUIPMENT_SET"
const HOOK_EVENT_SET := &"ON_EVENT_SET"
const HOOK_CARD_DISCARDED := &"ON_CARD_DISCARDED"
const HOOK_CARD_DESTROYED := &"ON_CARD_DESTROYED"

## ── 攻击 ──
const HOOK_ATTACK_CARD_PLAYED := &"ON_ATTACK_CARD_PLAYED"
const HOOK_ATTACK_DECLARED := &"ON_ATTACK_DECLARED"
const HOOK_ATTACK_RESPONSE_WINDOW := &"ON_ATTACK_RESPONSE_WINDOW"
const HOOK_ATTACK_MODIFIER_WINDOW := &"ON_ATTACK_MODIFIER_WINDOW"
const HOOK_ATTACK_HIT := &"ON_ATTACK_HIT"
const HOOK_ATTACK_MISS := &"ON_ATTACK_MISS"
const HOOK_ATTACK_RESOLVED := &"ON_ATTACK_RESOLVED"

## ── 伤害 ──
const HOOK_DAMAGE_MODIFIER_WINDOW := &"ON_DAMAGE_MODIFIER_WINDOW"
const HOOK_DAMAGE_DEALT := &"ON_DAMAGE_DEALT"

## ── 损伤 ──
const HOOK_BEFORE_DAMAGE_TOKEN_PLACED := &"ON_BEFORE_DAMAGE_TOKEN_PLACED"
const HOOK_AFTER_DAMAGE_TOKEN_PLACED := &"ON_AFTER_DAMAGE_TOKEN_PLACED"

## ── 装备 ──
const HOOK_EQUIPMENT_BROKEN := &"ON_EQUIPMENT_BROKEN"

## ── 胜负 ──
const HOOK_MECH_DESTROYED := &"ON_MECH_DESTROYED"

## ── 事件 ──
const HOOK_EVENT_TIMER_TICK := &"ON_EVENT_TIMER_TICK"
const HOOK_EVENT_TIMER_ZERO := &"ON_EVENT_TIMER_ZERO"

## ── 地图 ──
const HOOK_MECH_MOVED := &"ON_MECH_MOVED"
const HOOK_MAP_GOLD_MARKER_RESOLVED := &"ON_MAP_GOLD_MARKER_RESOLVED"
const HOOK_MAP_EVENT_MARKER_RESOLVED := &"ON_MAP_EVENT_MARKER_RESOLVED"
const HOOK_TRAP_EXPLODED := &"ON_TRAP_EXPLODED"
const HOOK_MAP_MARKERS_RESET := &"ON_MAP_MARKERS_RESET"

## ── 商店 ──
const HOOK_SHOP_INITIALIZED := &"ON_SHOP_INITIALIZED"
const HOOK_SHOP_CARD_BOUGHT := &"ON_SHOP_CARD_BOUGHT"
const HOOK_SHOP_REFRESHED := &"ON_SHOP_REFRESHED"
const HOOK_SHOP_REFILLED := &"ON_SHOP_REFILLED"

## ── 扩展 ──
const HOOK_STAT_RECALCULATE := &"ON_STAT_RECALCULATE"
const HOOK_STATUS_CHECK := &"ON_STATUS_CHECK"
const HOOK_SHOP_ACTION := &"ON_SHOP_ACTION"
const HOOK_EQUIPMENT_SOLD := &"ON_EQUIPMENT_SOLD"
const HOOK_ACTION_CARD_DRAWN := &"ON_ACTION_CARD_DRAWN"
const HOOK_ENERGY_APPLIED_TO_WEAPON := &"ON_ENERGY_APPLIED_TO_WEAPON"
